# version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - work

  redis:
    image: "redis:alpine"
    container_name: redis
    volumes:
      - redis_data:/var/lib/redis/data
    command: redis-server --bind redis 
    ports:
      - "6379:6379"
    networks:
      - work

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: volga
    networks:
      - work

  pgadmin:
    image: dpage/pgadmin4
    container_name: pga
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - work

  accounts_microservice:
    build:
      context: ./auth
    container_name: accounts_microservice
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - postgres
      - redis
    env_file:
      - ./auth/.env
    networks:
      - work

  # hospitals_microservice:
  #   build:
  #     context: ./hospitals
  #   container_name: hospitals_microservice
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./hospitals/.env
  #   networks:
  #     - work

networks:
  work:

volumes:
  postgres_data:
  redis_data: