"""asd

Revision ID: b11a57689553
Revises: 3fed2be1ce66
Create Date: 2024-10-25 19:03:06.887708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11a57689553'
down_revision: Union[str, None] = '3fed2be1ce66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hospitals_contactPhone_key', 'hospitals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hospitals_contactPhone_key', 'hospitals', ['contactPhone'])
    # ### end Alembic commands ###
