"""refreashTableAddAccess

Revision ID: 37a40951b565
Revises: fb421d6f9b2a
Create Date: 2024-09-29 18:02:05.597267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a40951b565'
down_revision: Union[str, None] = 'fb421d6f9b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('access_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_session', 'access_token')
    # ### end Alembic commands ###
