"""refreshSessionTable1

Revision ID: fb421d6f9b2a
Revises: cb5d5fe71909
Create Date: 2024-09-29 17:18:09.051189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb421d6f9b2a'
down_revision: Union[str, None] = 'cb5d5fe71909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_mtm_role_user_id_fkey', 'user_mtm_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_mtm_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_mtm_role', type_='foreignkey')
    op.create_foreign_key('user_mtm_role_user_id_fkey', 'user_mtm_role', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
