"""create_table_appointment

Revision ID: b7cc58fb0e56
Revises: 4cf8c60853fe
Create Date: 2024-10-10 22:12:02.040574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7cc58fb0e56'
down_revision: Union[str, None] = '4cf8c60853fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('timetable_id', sa.UUID(), nullable=False),
                    sa.Column('time', sa.TIMESTAMP(), nullable=False),
                    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    # ### end Alembic commands ###
