"""create_table_timetable

Revision ID: 4cf8c60853fe
Revises: 
Create Date: 2024-10-04 13:51:13.807721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4cf8c60853fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('hospitalId', sa.UUID(), nullable=False),
                    sa.Column('doctorId', sa.UUID(), nullable=False),
                    sa.Column('from', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('to', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('room', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_timetable_doctorId'), 'timetable', ['doctorId'], unique=False)
    op.create_index(op.f('ix_timetable_hospitalId'), 'timetable', ['hospitalId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_hospitalId'), table_name='timetable')
    op.drop_index(op.f('ix_timetable_doctorId'), table_name='timetable')
    op.drop_table('timetable')
    # ### end Alembic commands ###
