"""add column user_id in appointments

Revision ID: 1c17d94ead05
Revises: bb17d48b59a2
Create Date: 2024-10-14 19:33:50.318047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c17d94ead05'
down_revision: Union[str, None] = 'bb17d48b59a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'user_id')
    # ### end Alembic commands ###
