"""add delete cascade

Revision ID: bb17d48b59a2
Revises: fc5cb5360715
Create Date: 2024-10-14 18:43:40.318592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb17d48b59a2'
down_revision: Union[str, None] = 'fc5cb5360715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointment_timetable_id_fkey', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'timetable', ['timetable_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_timetable_id_fkey', 'appointment', 'timetable', ['timetable_id'], ['id'])
    # ### end Alembic commands ###
