"""create table history

Revision ID: 3dfed02e2655
Revises: 
Create Date: 2024-10-18 14:02:13.971093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3dfed02e2655'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pacientId', sa.UUID(), nullable=False),
                    sa.Column('hospitalId', sa.UUID(), nullable=False),
                    sa.Column('doctorId', sa.UUID(), nullable=False),
                    sa.Column('room', sa.String(), nullable=False),
                    sa.Column('data', sa.String(), nullable=False),
                    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_history_doctorId'), 'history', ['doctorId'], unique=False)
    op.create_index(op.f('ix_history_hospitalId'), 'history', ['hospitalId'], unique=False)
    op.create_index(op.f('ix_history_pacientId'), 'history', ['pacientId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_pacientId'), table_name='history')
    op.drop_index(op.f('ix_history_hospitalId'), table_name='history')
    op.drop_index(op.f('ix_history_doctorId'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
